### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by sambitdixit** [mmazi/rescu#10]
This is a cool framework. I liked the simplicity. Have you tried any performance benchmark of this against RestEasy or Jersey or CXF based clients ? Do you have plans to support SSL.

**Comment by mmazi** [comment]
Thanks for your comments! I haven't done any benchmarks, but it should be rather easy to do.

If by SSL you mean support for accessing services via HTTPS, it's already supported. You just need to make sure that a certificate from the server's certificate chain is in your trust store. Many Certificate Authority certificates already ship with the default Java trust store. Here's an example of HTTPS being used (you'll need to browse code a bit to see that, best done by cloning the XChange repo locally): https://github.com/timmolter/XChange/blob/develop/xchange-examples/src/main/java/com/xeiam/xchange/examples/bitstamp/account/BitstampAccountDemo.java

**Comment by sambitdixit** [comment]
Thanks..Have you got any use case where you need to pass extra header information not defined as part of @HeaderParam but directly sending the headers to server side REST API which the server side interceptors will instrospect to do certain check for example authorization based on a specific header field.  Using JAXRS proxy model, i was wondering unless we use a threadlocal to hold the headers, what will be the best way otherwise. Any thoughts ?

**Comment by mmazi** [comment]
There are several examples that use HTTP headers for authentication in https://github.com/timmolter/XChange/; see eg. https://github.com/timmolter/XChange/blob/develop/xchange-btce/src/main/java/com/xeiam/xchange/btce/BTCEAuthenticated.java which is an implementation of (the authenticated part of) https://btc-e.com/api/documentation.

What @HeaderParam does is that it causes rescu to send HTTP headers to the server; the point of rescu is to define this declaratively on the service interface instead of imperatively (directly).

If you have a concrete example of what you need to do, please send me the Rest API spec and I can help with defining the annotated Java interface.

**Comment by mmazi** [comment]
@sambitdixit, do you still have any open questions on this topic, or have I answered them and I can close this issue? Thanks!

**Comment by mmazi** [comment]
Closing since there seem to be no further issues.
