### ISSUE TITLE
Null returned by getJsonObject in JSONUtils

### ISSUE THREAD

**Issue by timmolter** [mmazi/rescu#12]
I wonder if the API could be improved by throwing an exception like on line 68 rather than returning null on line 60. If null is returned, the client will probably stumble upon a NPE. 

I'm referencing this issue: https://github.com/timmolter/XChange/issues/154

I think it would be better to throw a runtime exception with a nice desciption of what happened. It could even be checked in HttpTemplate before getJSONObject is called.

What do you think?

~Tim

**Comment by timmolter** [comment]
If we throw an exception, it should probably be a wrapped HttpException. Same for line 68 in JSONUtils. Perhaps all the raw RuntimeExceptions should be wrapped as well.

**Comment by mmazi** [comment]
I'll look into this. At first sight, returning null seems a valid response since null is the natural return value when the body is empty (no json data); is cases when jsonString may be empty, the client (caller) should be aware of this and expect a possible null result which in this case is not an exception, so no exception should be thrown.

But I'll have a look at the reference issue 154 and see what makes the most sense there.

**Comment by timmolter** [comment]
Yes, I like your arguments. I may just have to think of it in that way, and check for null on the client.

**Comment by mmazi** [comment]
I think you need to determine what causes the empty string to be passed to getJsonObject in the your case. There may be another indication that something is wrong in the http response (eg. response code or a header or something); this should be handled somewhere else, perhaps support for handling it should be added to rescu (eg. if it's a header). But I still think getJsonObject should return null if it gets an empty string as parameter.

**Comment by timmolter** [comment]
Yes, agreed. Why is it null? Is it because the server had some issue? Or because it simply had nothing to return? For now, I'm just going to check for null...
