### ISSUE TITLE
More advanced configuration of HttpsURLConnection (certificates)

### ISSUE THREAD

**Issue by martinzima** [mmazi/rescu#24]
Hello everybody,
first of all, thanks for the library, although I've just started using it, I kinda like its simplicity! (What do the CU letters in the name stand for by the way? :-D)

I am currently in a position where I need to be able to configure the used HTTP(S) connection in more detail. I would appreciate the possibility to manually set the SSL socket factory (HttpsURLConnection.setSSLSocketFactory) to my own instance. And when we are at this, I guess being able to override the HostnameVerifier (HttpsURLConnection.setHostnameVerifier) wouldn't do much harm either.

I need this to adjust the HTTPS certificate verification process to be able to use our self-signed certificates on our private servers (see http://developer.android.com/training/articles/security-ssl.html#CommonProblems for example). I will probably implement this somehow for myself in the meantime (might commit later?), but for the future users of ResCU, it would be nice if it already had this functionality in stock version.

What do you think?

**Comment by mmazi** [comment]
Hi @reddragcz,

yes, that sound like some very useful and needed functionality. I'd be most happy to accept a pull request from you, if you do implement this as you say! Otherwise I can add it myself (probably next week) since it doesn't seem like a lot of work.

This might also help with [a recurring issue](https://github.com/timmolter/XChange/issues/52) in XChange.

P.S. rescu stands for "REST Client Utility" :)

**Comment by mmazi** [comment]
Resolved in #25 .
