### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by andre77** [mmazi/rescu#30]
Hi,

indeed a nice lib!
but i just faced an issue, may be you can have a look at it:
si.mazi.rescu. HttpTemplate
Current line 145
https://github.com/mmazi/rescu/blob/develop/src/main/java/si/mazi/rescu/HttpTemplate.java#L145

throw new IOException(String.format("HTTP status code was %d; response body: %s", httpStatus, httpBody));

imho not the best way to throw a simple IOException with a message.
the client, in my case, needs to know, what went wrong, at least the http status is required...

than, does the error come from the http layer or the json parser? no way to know, parsing the message is not an option

best regards
andre

**Comment by mmazi** [comment]
Hi,

Thanks for reporting this! I'll have a look at this next week (I'm on vacation now).

**Comment by mmazi** [comment]
I definitely see your point, BTW. We had it done more like what you suggest a while ago (at least the http status was reported), but decided to only use IOExceptions to make things simple since these exceptions must be declared on the service interface.

I'll think about how to best solve this and get back to you. If you're sure how to best deal with it, a pull request will be welcome :)

**Comment by andre77** [comment]
Hi,
no idea, how to solve it best way...
one option could be to throw a subclass of IOException, which has the "status code" and "reason phrase" as fields, may be s.th. like this:

```
    @SuppressWarnings("serial")
    public class HTTPException extends IOException {
        private final int statusCode;
        private final String reasonPhrase;

        public HTTPException(int statusCode, String reasonPhrase) {
            super(String.format("HTTP status code was %d; reason phrase: %s", statusCode, reasonPhrase));
            this.statusCode = statusCode;
            this.reasonPhrase = reasonPhrase;
        }

        public int getStatusCode() { return statusCode; }
        public String getReasonPhrase() { return reasonPhrase; }
    }
```

so the interface is not changed, you can still catch IOException
but, additionally you can catch HTTPException, if you are interested in the status code
if this way is ok for, i can create a pull request, or feel free just to take it, not a big deal actually :-)

**Comment by mmazi** [comment]
Sounds like a good idea. If you can create a pull request from it that would be great!

**Comment by mmazi** [comment]
I've added `HttpStatusIOException` which does almost exactly what you suggested.

I also added an alternative solution for getting the http status code. You can declare interface methods that throw custom jackson-annotated exceptions and rescu will deserialize this exception object from the http response body; rescu already did this before. What I've added now is that if the custom exception implements `HttpStatusException`, rescu will provide the http status code in your custom exception. (You don't get the response body in this case, but this is not necessary since the response body data is already present in a deserialized form in the exception.)

**Comment by andre77** [comment]
Hi MMazi,
sorry, i actually wanted to create a pull request, but did not find time for that yet
