### ISSUE TITLE
Include Content-Length as a HeaderParam

### ISSUE THREAD

**Issue by zholmes1** [mmazi/rescu#57]
Is there any way to include Content-Length as a header? I am getting an HTTP status code 411 from Netagio, which means this parameter is required. When I look at the TRACE log I can see that it is not being included.

**Comment by mmazi** [comment]
The `Content-Length` header is omitted only if there is no content (ie. the content length is 0) -- [see here](/mmazi/rescu/blob/4d0945b3dcbfcc10e87129992767f0b1a2bd3656/src/main/java/si/mazi/rescu/HttpTemplate.java#L178).

Is your request body empty (eg. it's a GET request)? Can you try moving the `setRequestProperty` call (which sets the header) out of the `if (contentLength > 0)` block and see if that helps, then do a pull request?

**Comment by mmazi** [comment]
So, it would be great if you could test this and send a pull request, but if it seems to much hassle to do that, I can just move the setRequestProperty call (which sets the header) out of the if (contentLength > 0) block myself and commit it since this is very little work for me -- I don't see how this could do any harm and I think it's the way it should be according to the HTTP protocol anyway.

**Comment by zholmes1** [comment]
I think the problem has to do with how I'm sending my parameters. I was originally just generating the signature outside `NetagioParamsDigest`, so I moved everything there. But now when I have `@HeaderParam("Authorization") ParamsDigest signatureCreator`, it simply sends the ParamsDigest.toString() (com.xeiam.xchange.netagio.service.NetagioParamsDigest...) instead of the result of the digestParams method, as it seems to do for other exchanges. If I make a commit to my fork can you let me know what I'm doing wrong?

**Comment by zholmes1** [comment]
https://github.com/zholmes1/XChange/tree/netagio/xchange-netagio

**Comment by mmazi** [comment]
I'm looking at the code.. I don't see anything wrong with your code, but it seems to me there might be a bug in rescu. I'll look further tomorrow.

**Comment by mmazi** [comment]
Ah, got it: you should use `getHttpHeadersFromParams()` instead of `getAllHttpHeaders()` in `NetagioDigest`. Tested it and it seems to work.

The bug in rescu seems to be that the `getHttpHeadersFromParams()` is public, and it shouldn't be since it has side effects and should be called at a specific time -- definitely only after the digests have been created. I'll have a closer look tomorrow.

**Comment by zholmes1** [comment]
Ok great. That definitely fixes the issue I was having with the signature generation. However I'm still not getting a `Content-Length`. Thanks for looking into this for me!

**Comment by mmazi** [comment]
rescu will now send the Content-Lenght header. Hope this works for you, and doesn't break other people's stuff :) (It shouldn't)

**Comment by zholmes1** [comment]
I'm unable to get the newest version in Eclipse again, even after manually deleting rescu-1.7.2-SNAPSHOT.jar and updated my dependencies. I will try again tomorrow morning.

**Comment by zholmes1** [comment]
It seems like it is impossible to manually set the `Content-Length`. For instance, this prints `null`.

```
connection.setRequestProperty("Content-Length", Integer.toString(contentLength));
log.trace(connection.getRequestProperty("Content-Length"));
```

I did find one workaround which is to send a dummy string as a `FormParam`. While not ideal, this does force HttpURLConnection to send the Content-Length parameter.
