### ISSUE TITLE
Mapping HTTP response headers

### ISSUE THREAD

**Issue by rafalkrupinski** [mmazi/rescu#72]
Hi

Can Rescu map HTTP response parameters?

**Comment by mmazi** [comment]
Rescu only (and only to some extent) handles the `Content-Type` and `Content-Encoding` header; it generally ignores other HTTP headers.

There is an undocumented feature though where rescu can, in case that it will throw an exception (instead of returning normally) from a HTTP method invocation, populate the exception with response headers. The exception type just needs to be `HttpResponseAware`. If this sounds like what you need, let me know and I'll write some docs. There is also an example or two in the tests towards the end of `RestInvocationHandlerTest`.

Rescu currently does not provide a way to capture HTTP headers with regular (non-exception) returns.

**Comment by rafalkrupinski** [comment]
The service I'm using puts throttling data and the error messages in the headers, so I guess while it would be nice to have throttling data, mapping the error message will be really useful.

**Comment by mmazi** [comment]
If I understand your case correctly, you can have rescu recognize the erroneous response by HTTP error code (which it does automatically) or by response body contents (eg. by throwing a `ExceptionalReturnContentException` in the regular response object constructor), which will make rescu throw your custom `HttpResponseAware` exception that you declare on the proxy method. You can then catch this exception and read all HTTP response headers from it.

I don't quite understand what you mean by 'mapping' though.

**Comment by rafalkrupinski** [comment]
s/mapping/including in the exception object/

**Comment by mmazi** [comment]
Cool, so rescu has what you need? You should also be able to get the throttling data this way.

**Comment by rafalkrupinski** [comment]
But I can only get the throttling data in case of a HTTP error, right?

**Comment by mmazi** [comment]
That's right, if I understand your case correctly.
