### ISSUE TITLE
Dealing with empty json 

### ISSUE THREAD

**Issue by crypto-sporidium** [mmazi/rescu#74]
Hello.  I don't understand how you configure mappings when the getHttpBody() in the server response is effectively empty then can not be mapped. This is causing me problems in XChange at the moment.

You have checks here 
si.mazi.rescu.ResponseReader

  if (isHttpStatusPass) {
            if (httpBody == null || httpBody.length() == 0 ){
                return null;
            } else { 
                 /// do the mapping ??

But the only way I can see of dealing with getting an empty json object back is to do something like this.

 if (isHttpStatusPass) {
            if (httpBody == null || httpBody.length() == 0 || httpBody.toString().equals("[]")){
                return null;
            } else {

**Comment by mmazi** [comment]
If I understand correctly, you suggest that "[]", i.e. an empty jason array, should be converted to Java null object? While this may be desirable in some special cases, I don't think this is the way to go in the general case. Generally, the correct Java representation for an empty json array is an empty Java array (T[]) or an empty Collection.

Can you provide more details on where in XChange you would need this functionality and why, i.e. what the exact problem is?

One possible way to tackle this in a specific case could be to configure Jackson so that it converts empty json arrays to null; I don't know whether Jackson supports this, but I suspect it might (please see Jackson docs).

**Comment by crypto-sporidium** [comment]
Well I'm open to any suggestion to just try and make the api work
The problem is related to an issue I posted 2 days ago

https://github.com/timmolter/XChange/issues/1167

according the XChange specification they expect a null object to be returned when there is no trade history. The problem is you get the empty json array from the exchange then as far as I can see rescu throws a  jackson mapping exception before that and you have no idea why.   I'm sure they may be some other way of dealing with the issue and if you haven any ideas please share.  I was unable to get the logging working in rescu after spending hours reading the log4j documentation so eventually I just forked the package and wrote a system.out.println()  just to be able to see what was coming back from the exchange and picked this up.  So yeah the idea spending a few days reading the jackson docs just to figure out if this is even possible is not something I want to do at this point.

I did find one mention of how to prevent it writing null map values but this is not helping me at this point
http://stackoverflow.com/questions/11449211/how-to-prevent-null-values-inside-a-map-and-null-fields-inside-a-bean-from-getti

**Comment by mmazi** [comment]
This is a Poloniex-specific issue that is being solved in https://github.com/timmolter/XChange/issues/1167 .

For furture reference, the solution seems to be to use Jackson's `DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT`.
